plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from

url: https://kiddy-trick.ru

title: ""

collections:
  catalog:
    output: true

social:
  name: KiddyTrick
  links:
    - https://www.facebook.com/kiddy.trick
    - http://instagram.com/kiddy.trick/
    
logo: /images/logo-color.svg

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/banner-myagkie-knizhki.jpg