plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  
collections:
  catalog:
    output: true

social:
  name: Kiddy-Trick
  links:
    - https://www.facebook.com/kiddy.trick
    - https://www.instagram.com/kiddy.trick/

logo: /images/logo_for_links.jpg
url: https://kiddy-trick.ru

title: ""
lang: "ru_RU"

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/logo_for_links.jpg
